INSERT INTO "modes" VALUES(1,'Prism',NULL);
INSERT INTO "modes" VALUES(2,'SXD',NULL);
INSERT INTO "modes" VALUES(3,'LXD1.9',NULL);
INSERT INTO "modes" VALUES(4,'SL',NULL);
INSERT INTO "modes" VALUES(5,'LXD2.3',NULL);
INSERT INTO "modes" VALUES(6,'Echelle',NULL);
INSERT INTO "modes" VALUES(7,'LL',NULL);
INSERT INTO "modes" VALUES(8,'VPH Grism',NULL);
INSERT INTO "modes" VALUES(9,'Red Grism',NULL);
